quarkus.banner.path=banner.txt

%dev.quarkus.http.port=8082

mp.messaging.incoming.creation.connector=smallrye-kafka
mp.messaging.incoming.creation.topic=guess.creation
mp.messaging.incoming.creation.auto.offset.reset=earliest

mp.messaging.incoming.proposal.connector=smallrye-kafka
mp.messaging.incoming.proposal.topic=guess.proposal
mp.messaging.incoming.proposal.auto.offset.reset=earliest

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST

guess.auth.domain=keycloak.oxiane-formation.fr/realms/guess-game
guess.auth.client.secret=y0WornDIt1yTEFgoHN0JDKWh8BFGyNpi
guess.auth.client.id=guess-game-dev

%dev.quarkus.oidc.auth-server-url=https://${guess.auth.domain}
%dev.quarkus.oidc.client-id=${guess.auth.client.id}
%dev.quarkus.oidc.credentials.secret=${guess.auth.client.secret}

%prod.quarkus.oidc.auth-server-url=https://${guess.auth.domain}
%prod.quarkus.oidc.client-id=${guess.auth.client.id}
%prod.quarkus.oidc.credentials.secret=${guess.auth.client.secret}

quarkus.oidc.authentication.scopes=profile,email,openid